user_badges.badge_type.*:
  type: config_entity
  label: 'Badge type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    automatic:
      type: boolean
      label: 'Automatic Badge Assignment'
